<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="6" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-20T18:54:33 IST" name="Default suite" finished-at="2023-10-20T19:01:07 IST" duration-ms="393212">
    <groups>
    </groups>
    <test started-at="2023-10-20T18:54:33 IST" name="Default test" finished-at="2023-10-20T19:01:07 IST" duration-ms="393212">
      <class name="com.Tests.LoginTest">
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:54:33 IST" name="SetUp" finished-at="2023-10-20T18:54:58 IST" duration-ms="24709" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.ValidateLoginPageLogo() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="ValidateLoginPageLogo()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:54:58 IST" name="ValidateLoginPageLogo" finished-at="2023-10-20T18:55:04 IST" duration-ms="6133" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.Tests.LoginTest.ValidateLoginPageLogo(LoginTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLoginPageLogo -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:04 IST" name="TearDown" finished-at="2023-10-20T18:55:13 IST" duration-ms="9178" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:13 IST" name="SetUp" finished-at="2023-10-20T18:55:30 IST" duration-ms="16576" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.ValidateLoginPageTitle()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="ValidateLoginPageTitle()[pri:1, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:30 IST" name="ValidateLoginPageTitle" finished-at="2023-10-20T18:55:30 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLoginPageTitle -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:30 IST" name="TearDown" finished-at="2023-10-20T18:55:39 IST" duration-ms="8564" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:39 IST" name="SetUp" finished-at="2023-10-20T18:55:54 IST" duration-ms="15665" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.ValidateLoginPageURL()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="ValidateLoginPageURL()[pri:2, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:54 IST" name="ValidateLoginPageURL" finished-at="2023-10-20T18:55:54 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLoginPageURL -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:55:54 IST" name="TearDown" finished-at="2023-10-20T18:56:03 IST" duration-ms="8387" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:56:03 IST" name="SetUp" finished-at="2023-10-20T18:56:23 IST" duration-ms="20502" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.LoginWithValidCredential() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginWithValidCredential()[pri:3, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:56:23 IST" name="LoginWithValidCredential" finished-at="2023-10-20T18:56:35 IST" duration-ms="11556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithValidCredential -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:56:35 IST" name="TearDown" finished-at="2023-10-20T18:56:43 IST" duration-ms="8579" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:56:43 IST" name="SetUp" finished-at="2023-10-20T18:56:58 IST" duration-ms="15070" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.LoginWithInvalidCredential()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginWithInvalidCredential()[pri:4, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:56:58 IST" name="LoginWithInvalidCredential" finished-at="2023-10-20T18:57:02 IST" duration-ms="3308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithInvalidCredential -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:57:02 IST" name="TearDown" finished-at="2023-10-20T18:57:10 IST" duration-ms="8525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:57:10 IST" name="SetUp" finished-at="2023-10-20T18:57:30 IST" duration-ms="19460" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.LoginWithBlankCredentials()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginWithBlankCredentials()[pri:5, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:57:30 IST" name="LoginWithBlankCredentials" finished-at="2023-10-20T18:57:31 IST" duration-ms="1535" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Requir] but found [Required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Requir] but found [Required]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.Tests.LoginTest.LoginWithBlankCredentials(LoginTest.java:103)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithBlankCredentials -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:57:31 IST" name="TearDown" finished-at="2023-10-20T18:57:40 IST" duration-ms="8587" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:57:40 IST" name="SetUp" finished-at="2023-10-20T18:58:14 IST" duration-ms="34102" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.LoginWithUserNameOnly()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginWithUserNameOnly()[pri:6, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:58:14 IST" name="LoginWithUserNameOnly" finished-at="2023-10-20T18:58:15 IST" duration-ms="1214" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Requir] but found [Required]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Requir] but found [Required]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.Tests.LoginTest.LoginWithUserNameOnly(LoginTest.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithUserNameOnly -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:58:15 IST" name="TearDown" finished-at="2023-10-20T18:58:23 IST" duration-ms="8307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:58:23 IST" name="SetUp" finished-at="2023-10-20T18:59:03 IST" duration-ms="39575" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.LoginWithEnterPasswordOnly()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="LoginWithEnterPasswordOnly()[pri:7, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:59:03 IST" name="LoginWithEnterPasswordOnly" finished-at="2023-10-20T18:59:04 IST" duration-ms="1201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginWithEnterPasswordOnly -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:59:04 IST" name="TearDown" finished-at="2023-10-20T18:59:13 IST" duration-ms="9228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:59:13 IST" name="SetUp" finished-at="2023-10-20T18:59:51 IST" duration-ms="37496" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.ValidateForgottenPasswordLink()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="ValidateForgottenPasswordLink()[pri:8, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:59:51 IST" name="ValidateForgottenPasswordLink" finished-at="2023-10-20T18:59:55 IST" duration-ms="4294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateForgottenPasswordLink -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T18:59:55 IST" name="TearDown" finished-at="2023-10-20T19:00:07 IST" duration-ms="12180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUp(java.lang.reflect.Method)[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T19:00:07 IST" name="SetUp" finished-at="2023-10-20T19:00:56 IST" duration-ms="48622" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Tests.LoginTest.ValidateOrangeHRMIncLink()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="ValidateOrangeHRMIncLink()[pri:9, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T19:00:56 IST" name="ValidateOrangeHRMIncLink" finished-at="2023-10-20T19:00:58 IST" duration-ms="1639" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.orangehrm.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.orangehrm.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.Tests.LoginTest.ValidateOrangeHRMIncLink(LoginTest.java:157)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateOrangeHRMIncLink -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.Tests.LoginTest@78e4deb0]" started-at="2023-10-20T19:00:58 IST" name="TearDown" finished-at="2023-10-20T19:01:07 IST" duration-ms="8838" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.Tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
